### ISSUE TITLE
Random extra pixels in output

### ISSUE THREAD

**Issue by aDrunkLittleDerp** [Silverfeelin/Starbound-Hatter#7]
I've noticed that some Hatter drawables don't match the input image. This started occurring with the update that used shortened colors in the drawable

For example, making a drawable with this image...
![Original Image and Hatter Preview](https://user-images.githubusercontent.com/17101520/58201625-24c24f80-7c9b-11e9-9fe5-1eb44f808d11.png)

...results in this image (which has an extra pixel in it) when the item is spawned into the game:
![Hatter Output](https://user-images.githubusercontent.com/17101520/58201621-22f88c00-7c9b-11e9-80be-82187697779a.png)
(Random pixel highlighted in red)
![Output Error Highlighted In Red](https://user-images.githubusercontent.com/17101520/58201628-25f37c80-7c9b-11e9-8c52-b72de87e5bb5.png)

Enlarged image (input, output, highlight):
![Screen Shot 2019-05-22 at 2 02 13 PM (2)](https://user-images.githubusercontent.com/17101520/58201914-e4170600-7c9b-11e9-9545-fd8717a4e9b6.png)

**Comment by Silverfeelin** [comment]
Looks like an issue with the way Starbound scales images (which I use to create a gradient).

Here we have a simple raster (upscaled x16) using the dimensions of your image (12x12), generated by the new algorithm:
![image](https://user-images.githubusercontent.com/17196309/58271838-3dab2d80-7d8d-11e9-8729-7d0a15752709.png)

As we can see in the same location as the highlighted pixel on your image, the color of the bad pixel matches the one next to them (in reality the one below it, which explains the problem). I'm guessing this is due to a rounding error in the Starbound engine (where it turns the directives into an image to render).

Testing this on the intended dimensions for the Hatter (43x43) shows us similar results, as seen in the below image (upscaled x8).
![image](https://user-images.githubusercontent.com/17196309/58271462-61ba3f00-7d8c-11e9-9246-36500c7e2fa0.png)

And here's double that (86x86, upscaled x4):
![image](https://user-images.githubusercontent.com/17196309/58271650-cb3a4d80-7d8c-11e9-81e8-9fec247b341d.png)
At these dimensions I'm guessing the scaling done by the game is less prone to rounding errors.

When testing I considered this might be a problem but couldn't find any odd looking results. Looking back at it I never really gave it a go with pixels at the very edges of the image.

A simple workaround would be to add some padding around the edges of your image, the hatter isn't really intended for generic drawables and most hats don't stretch all the way to the edges of the 'normal' 43x43 dimensions. That said, I will introduce a legacy option to use the old method.

Drawables Generator for Windows with various algorithms (including this one and the old one):  
https://github.com/Silverfeelin/Starbound-DrawablesGenerator
